### PR TITLE
Additional test cases

### PR DESCRIPTION
**Pull request by Twilight-Shuxin**
Additional test cases originated from bug reports.

### CODE REVIEW

**Comment by Twilight-Shuxin** [comment]
@michaelhkay Hi, may I ask if you would have time to help me review this pull request? Or is there anything I could do to improve it? Thanks a lot!

**Comment by michaelhkay** [comment]
Looks fine to me - thanks for submitting them. I haven't run them yet, it's easiest to merge them first and then pull the changes.

**Comment by michaelhkay** [comment]
All new tests passing on SaxonJ-11.

**Comment by Twilight-Shuxin** [comment]
Thanks a lot for the review!

**Pull request merged**
